apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-chrony
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/chrony.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,c2VydmVyIDAucG9vbC5udHAub3JnIGlidXJzdApzZXJ2ZXIgMS5wb29sLm50cC5vcmcgaWJ1cnN0Cm1ha2VzdGVwIDEuMCAzCnJ0Y3N5bmMKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdAoK
