apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: set-core-user-password
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
      - name: core
        passwordHash: $6$PSKH.pPdf165Jlj0$XsdFJ.9Oja/xtmN1hiwgC2Ck93Wn32AdbMcq1bhxhy0oxaITKdE.atllNS63J9lbfsYs5W4U9fOMfZsS074OU1
