apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: openshift-gitops
spec:
  project: test-project

  source:
    repoURL: https://github.com/mkaram007/demo-web
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo-web-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true