apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
        - name: httpd
          image: registry.redhat.io/ubi8/httpd-24:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: html
              mountPath: /var/www/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: web-demo-pvc