apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 5Gi # Adjust storage capacity as needed
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany, ReadOnlyMany depending on your needs
  persistentVolumeReclaimPolicy: Retain # Or Delete, Recycle
  hostPath:
    path: /mnt/data/hostpath-volume # The path on the host node
    type: DirectoryOrCreate # Ensures the directory exists or creates it