apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-demo-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: hostpath-pv